### PR TITLE
Full Text Search for Courses

### PR DESCRIPTION
**Pull request by zhemao**
Currently not documented, since the search endpoint is implemented very differently from the courses and sections endpoints. The search endpoint is basically a frontend to elasticsearch's query string search.

### CODE REVIEW

**Comment by znewman01** [comment]
could use a rebase, but lgtm otherwise

**Comment by brishin** [comment]
Looks good. Does this also solve duplication of courses when we want to update the full text search?

**Comment by brishin** [comment]
Also @zhemao if you can get this up and running soon, the bbeta branch on Courses should be much closer to a launch.

**Comment by zhemao** [comment]
Okay, I've rebased and merged with master. Let's see about deploying it. I'm pretty sure there is no duplication here, because my import script updates on the same ids.

**Comment by zhemao** [comment]
So, how are we going to deploy this?

**Comment by brishin** [comment]
Moving the conversation to gchat

**Pull request closed without merging**
